default: &default
  adapter: postgresql
  host: ec2-54-197-250-52.compute-1.amazonaws.com	
  username: wqxnhhvzskuqss
  password: S7WrKnuTby6RfFEvYuC-QSV7oK
  pool: 5

development:
  <<: *default
  database: dahv68cbo08sv3
test:
  <<: *default
  database: dahv68cbo08sv3

production:
  <<: *default
  database: dahv68cbo08sv3
